FROM debian:stretch

ARG BUNDLE_DIR

RUN apt-get update && apt-get install -y ca-certificates s3cmd

# This is a template Dockerfile for the bundle's invocation image
# You can customize it to use different base images, install tools and copy configuration files.
#
# Porter will use it as a template and append lines to it for the mixins
# and to set the CMD appropriately for the CNAB specification.
#
# Add the following line to porter.yaml to instruct Porter to use this template
# dockerfile: Dockerfile.tmpl

COPY .cnab /cnab

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY . $BUNDLE_DIR

#RUN apt-get update && apt-get install -y wget
#RUN wget https://github.com/digitalocean/doctl/releases/download/v1.28.0/doctl-1.28.0-linux-amd64.tar.gz
#RUN tar xf doctl-1.28.0-linux-amd64.tar.gz
#RUN mv doctl /usr/local/bin